// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: arith_service.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int32 `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
}

func (x *ProtoArgs) Reset() {
	*x = ProtoArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arith_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoArgs) ProtoMessage() {}

func (x *ProtoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_arith_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoArgs.ProtoReflect.Descriptor instead.
func (*ProtoArgs) Descriptor() ([]byte, []int) {
	return file_arith_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoArgs) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *ProtoArgs) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type ProtoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C int32 `protobuf:"varint,1,opt,name=C,proto3" json:"C,omitempty"`
}

func (x *ProtoReply) Reset() {
	*x = ProtoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arith_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoReply) ProtoMessage() {}

func (x *ProtoReply) ProtoReflect() protoreflect.Message {
	mi := &file_arith_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoReply.ProtoReflect.Descriptor instead.
func (*ProtoReply) Descriptor() ([]byte, []int) {
	return file_arith_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoReply) GetC() int32 {
	if x != nil {
		return x.C
	}
	return 0
}

var File_arith_service_proto protoreflect.FileDescriptor

var file_arith_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x72, 0x69, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x27, 0x0a,
	0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x42, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x42, 0x22, 0x1a, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x43, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_arith_service_proto_rawDescOnce sync.Once
	file_arith_service_proto_rawDescData = file_arith_service_proto_rawDesc
)

func file_arith_service_proto_rawDescGZIP() []byte {
	file_arith_service_proto_rawDescOnce.Do(func() {
		file_arith_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_arith_service_proto_rawDescData)
	})
	return file_arith_service_proto_rawDescData
}

var file_arith_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_arith_service_proto_goTypes = []any{
	(*ProtoArgs)(nil),  // 0: client.ProtoArgs
	(*ProtoReply)(nil), // 1: client.ProtoReply
}
var file_arith_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arith_service_proto_init() }
func file_arith_service_proto_init() {
	if File_arith_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_arith_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProtoArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arith_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProtoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_arith_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arith_service_proto_goTypes,
		DependencyIndexes: file_arith_service_proto_depIdxs,
		MessageInfos:      file_arith_service_proto_msgTypes,
	}.Build()
	File_arith_service_proto = out.File
	file_arith_service_proto_rawDesc = nil
	file_arith_service_proto_goTypes = nil
	file_arith_service_proto_depIdxs = nil
}
